server:
  port: ${SERVER_PORT}

spring:
  application:
    name: hub-service
  datasource:
    url: jdbc:mariadb://hub-mariadb:3310/hub-database?useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: redis
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER}
#    register-with-eureka: false
#    fetch-registry: false



#management:
#  zipkin:
#    tracing:
#      endpoint: "http://zipkin:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0