server:
  port: ${SERVER_PORT}

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

#  config:
#    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        # 로그인이 필요하지 않은 요청
        - id: user-service-signup
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/signup
            - Method=POST
        - id: user-service-login
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/login
            - Method=POST
        - id: user-service-test
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/hello2
            - Method=GET
        - id: user-service-logout
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/logout
            - Method=POST
        - id: user-service-token-reissue
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/token/reissue
            - Method=POST
        - id: delivery-service-assign-manager
          uri: lb://delivery-service
          predicates:
            - Path=/delivery-service/api/send
            - Method=GET
#        - id: hub-service
#          uri: lb://hub-service
#          predicates:
#            - Path=/hub-service/api/**
        # 로그인 필요한 요청(토큰 검증 필터 존재)
        - id: user-service # 라우트 식별자
          uri: lb://user-service  # 'user-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/user-service/api/**  # 경로로 들어오는 요청을 이 라우트로 처리
          filters:
            - name: AuthPermissionPreFilter
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/slack-service/api/**
          filters:
            - name: AuthPermissionPreFilter
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store-service/api/**
          filters:
            - name: AuthPermissionPreFilter
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
              - Path=/delivery-service/api/**
          filters:
              - name: AuthPermissionPreFilter

        # product-service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/**
          filters:
            - name: AuthPermissionPreFilter

        - id: slack-service-get-messages
          uri: lb://slack-service
          predicates:
            - Path=/slack-service/api/**
          filters:
            - name: AuthPermissionPreFilter
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hub-service/api/**
          filters:
            - name: AuthPermissionPreFilter

      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
  jwt:
    secret: ${JWT_SECRET}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # JPA 자동설정 무시. JPA가 필요하지 않기때문
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
    register-with-eureka: true
    fetch-registry: true

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0