services:
  mariadb:
    image: mariadb:10.11
    container_name: slack-mariadb
    restart: always
    environment:
      MARIADB_DATABASE: slack-database
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - gaebal-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: slack-backend
    container_name: slack-backend
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://slack-mariadb:3306/slack-database?useSSL=false
      SPRING_DATASOURCE_USERNAME: slackUser
      SPRING_DATASOURCE_PASSWORD: 19890422pkl!
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_SERVER: http://eureka-server:19090/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - gaebal-network

networks:
  gaebal-network:
    external: true