server:
  port: ${SERVER_PORT}

spring:
  application:
    name: product-service
  config:
    import: optional:file:.env[.properties]
  # MariaDB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  # Redis
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
      username: default
      password: systempass

  # Kafka
  kafka:
    bootstrap-servers: localhost:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.MariaDBDialect


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}


# zipkin
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0
