services:
  mariadb:
    image: mariadb:10.11
    container_name: hub-mariadb
    restart: always
    environment:
      MARIADB_DATABASE: hub-database
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    networks:
      - gaebal-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: hub-backend
    container_name: hub-backend
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mariadb://hub-mariadb:3306/hub-database?useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_URL: ${KAFKA_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_SERVER: http://eureka-server:19090/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      NAVER_DIRECTION5_CLIENT_ID: ${Client_ID}
      NAVER_DIRECTION5_CLIENT_SECRET: ${Client_Secret}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - gaebal-network

networks:
  gaebal-network:
    external: true