services:
  mariadb:
    image: mariadb:10.11
    container_name: user-mariadb
    restart: always
    environment:
      MARIADB_DATABASE: user-database
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - gaebal-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-backend
    container_name: user-backend
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://user-mariadb:3306/user-database?useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_SERVER: ${EUREKA_SERVER}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: ${ZIPKIN_URL}
    ports:
      - "19092:19092"
    networks:
      - gaebal-network

networks:
  gaebal-network:
    external: true