services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "19091:19091"
    env_file:
      - .env
    networks:
      - gaebal-network

networks:
  gaebal-network:
    external: true