server:
  port: 19096
  address: 0.0.0.0

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:mariadb://delivery-mariadb:3306/delivery-database?useSSL=false
    username: deliveryUser
    password: 19890422pkl!
    driver-class-name: org.mariadb.jdbc.Driver

  # Redis
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
#      username: default
#      password: systempass

  # Kafka
  kafka:
    url: ${KAFKA_BOOTSTRAP_SERVERS}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
    register-with-eureka: true
    fetch-registry: true

naver:
  direction5:
    client-id: ${Client_ID}
    client-secret: ${Client_Secret}

jwt:
  secret: ${JWT_SECRET}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true